sudo: false
language: java
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "thiagogarbazza-github"
    token:
      secure: ${SONAR_TOKEN}

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

before_install:
  - mvn clean

install:
  - mvn compile

script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn sonar:sonar

after_success:
  - echo -e ${GPG_IMPORT} > target/gpg.asc
  - gpg --fast-import target/gpg.asc
  - mvn deploy --settings artifacts/ci/maven-settings.xml

deploy:
  skip_cleanup: true
  on:
    tags: true
